config/routes.rb
Rails.application.routes.draw do
	
	get 'welcome/index'
	get 'users/login' 
	post 'users/loggedin'
	resources :users
	
	root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	#has_secure_password
	validates :email_id, :password, :first_name, :last_name, :dob, :city, :country, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index

	end

	def new
		@user = User.new
	end #new
	
	def create
		@user = User.new(user_params)
 		if @user.save
 			render 'login'
		else
			render 'new'
		end
	end #create
 
 	def show
	 	#byebug
 	   @user = User.find(params[:email_id])
  end #show
	
	def login
		#@user = User.find(params[:email_id, :password])
		#session[:current_user_id] = @user.id
	end  #login
	
	def loggedin
		@user = User.find(params[:email_id, :password])
		if user
			render 'show'
		else
			render 'login'	
		end	
		#session[:current_user_id] = @user.email_id
  	
	end

	def update
		render 'show'
	end

	def logout
		session[:current_user_id] = nil
		render 'login'
	end
	
	private 
		def user_params
			params.require(:user).permit(:email_id, :password, :first_name, :last_name, :dob, :city, :country)
		end #user_params
end # class

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatbook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<h1> Index </h1>

app/views/users/login.html.erb
<h1>Login Page </h1>
<%= form_with model: @user, url:users_loggedin_path, local: true do |form| %>
	<p>
		<%= form.label :email_id,"Email_id" %><br>
		<%= form.text_field :email_id %>
	</p>
 	<p>
		<%= form.label :password,"Password" %><br>
		<%= form.text_field :password %>
	</p>
	<p>
		<%= form.submit "click" %>
	</p>

<% end %>

app/views/users/new.html.erb
<h1>SignUp Page </h1>
<%= form_with model: @user, local: true do |form| %>
	
	<p>
		<%= form.label :email_id,"Email_id" %><br>
		<%= form.text_field :email_id %>
	</p>
 	
 	<p>
		<%= form.label :password,"Password" %><br>
		<%= form.text_field :password %>
	</p>
 	
 	<p>
		<%= form.label :first_name,"First Name" %><br>
		<%= form.text_field :first_name %>
	</p>
 	
 	<p>
    <%= form.label :last_name,"Last Name" %><br>
    <%= form.text_field :last_name %>
  </p>
 	
 	<p>
    <%= form.label :dob, "DOB" %><br>
    <%= form.text_field :dob %>
  </p>
 	
 	<p>
    <%= form.label :city,"City" %><br>
    <%= form.text_field :city %>
  </p>
 	
 	<p>
    <%= form.label :country,"Country" %><br>
    <%= form.text_field :country %>
  </p>
 	
	<p>
		<%= form.submit %>
	</p>

<% end %>

app/views/users/show.html.erb
<h1> this is your homepage </h1>

app/views/welcome/index.html.erb
<h1> Welcome to chatbook </h1>
<%= link_to ('Login Page'), users_login_path %> 


<h1> ..........</h1>
<%= link_to 'click here to Sign in ', new_user_path %>